name: Remote Affiliate Build
on:
  repository_dispatch:
    types: [build-apk]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Unzip and Organize
        run: |
          mkdir temp_zip
          unzip -q Rukaze_App.zip -d temp_zip
          GRADLEW_PATH=$(find temp_zip -name "gradlew" | head -n 1)
          if [ -z "$GRADLEW_PATH" ]; then exit 1; fi
          cp -rn $(dirname "$GRADLEW_PATH")/* .
          rm -rf temp_zip

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make Gradlew Executable
        run: |
          chmod +x gradlew
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Build with Gradle
        run: |
          ./gradlew assembleDebug \
            -PAFF_ID=${{ github.event.client_payload.aff_id }} \
            -PAPK_OWNER="${{ github.event.client_payload.apk_owner }}" \
            --no-daemon
            
      - name: Rename & Release
        run: |
          mkdir -p final_apk
          # We use quotes to handle names that might have spaces
          mv app/build/outputs/apk/debug/app-debug.apk final_apk/${{ github.event.client_payload.apk_owner }}.apk

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0
          files: final_apk/${{ github.event.client_payload.apk_owner }}.apk
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
